- targets:
    - '10.0.101.26:9100'
    - '10.0.101.243:9100'
    - '10.0.101.54:9100'
    - '10.0.101.152:9100'
    - '10.0.101.149:9100'
    - '10.0.101.230:9100'
    - '10.0.101.90:9100'
    - '10.0.101.142:9100'
  labels:
    name: 'backend-api-1'
    environment: 'production'
    region: 'ap-northeast-2'
    cluster: 'backend'
    service: 'api'

- targets:
    - '10.0.101.28:9100'
    - '10.0.101.182:9100'
  labels:
    name: 'frontend-next-1'
    environment: 'production'
    region: 'ap-northeast-2'
    cluster: 'frontend'
    service: 'next'

- targets:
    - '10.0.101.58:9100'
    - '10.0.101.125:9100'
    - '10.0.101.202:9100'
  labels:
    name: 'db-mongodb-1'
    environment: 'production'
    region: 'ap-northeast-2'
    cluster: 'database'
    service: 'mongodb'

- targets:
    - '10.0.101.34:9100'
    - '10.0.101.159:9100'
    - '10.0.101.154:9100'
    - '10.0.101.245:9100'
    - '10.0.101.212:9100'
    - '10.0.101.239:9100'
  labels:
    name: 'db-redis-1'
    environment: 'production'
    region: 'ap-northeast-2'
    cluster: 'database'
    service: 'redis'

- targets:
    - '10.0.101.83:9100'
  labels:
    name: 'monitoring-server'
    environment: 'production'
    region: 'ap-northeast-2'
    cluster: 'monitoring'
    service: 'observability'
