global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

rule_files:
  - '/etc/prometheus/rules.yml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets:
          - '10.0.101.26:5001'
          - '10.0.101.243:5001'
          - '10.0.101.54:5001'
          - '10.0.101.152:5001'
          - '10.0.101.149:5001'
          - '10.0.101.230:5001'
          - '10.0.101.90:5001'
          - '10.0.101.142:5001'
        labels:
          application: 'ktb-chat-backend'
          environment: 'production'

  - job_name: 'mongodb'
    static_configs:
      - targets:
          - '10.0.101.58:9216'
          - '10.0.101.125:9216'
          - '10.0.101.202:9216'
        labels:
          environment: 'production'

  - job_name: 'redis'
    static_configs:
      - targets:
          - '10.0.101.34:9121'
          - '10.0.101.159:9121'
          - '10.0.101.154:9121'
          - '10.0.101.245:9121'
          - '10.0.101.212:9121'
          - '10.0.101.239:9121'
        labels:
          environment: 'production'

  - job_name: 'node-exporter'
    file_sd_configs:
      - files:
          - '/etc/prometheus/targets/node-exporters.prod.yml'
        refresh_interval: 5s
